server:
  port: 8080

spring:
  application:
    name: money
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_money?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: user_money
    password: 1004
  thymeleaf:
    cache: false

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update